# Generated by Django 5.0.6 on 2024-06-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file_upload',
        ),
    ]
